import { SiteFooter, SiteHeader } from '@/components/site-header';
import { siteUrl } from '@/lib/library';
import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'About and Methodology', description: 'How Scholarship Atlas researches, verifies and maintains official-source graduate funding records.', alternates: { canonical: `${siteUrl}/about/` } };

export default function AboutPage() {
  return <main><SiteHeader /><article className="about-page site-shell"><header><p className="kicker">About Scholarship Atlas</p><h1>A research directory built to make graduate funding easier to find.</h1><p className="about-lede">Scholarship Atlas tracks funding opportunities for Master&apos;s and PhD study in data, AI and related fields, with the source material kept close to every record.</p></header><section><p className="kicker">Why it exists</p><h2>Good information should not be hard to reach.</h2><p>I initially used an AI agent to collect information about Data and AI scholarships. The useful work was not merely finding opportunities, but checking programme pages, scholarship terms, admissions requirements and official application links together.</p><p>That process made it clear that one person should not gatekeep a growing body of curated scholarship information. Scholarship Atlas is the public version of that work: a place to browse, compare and verify funding routes without losing the source trail.</p></section><section><p className="kicker">How verification works</p><h2>Official sources first, uncertainty labelled.</h2><p>Each public record links to the provider pages used for funding, programme and admissions claims. A record&apos;s last checked date identifies when those pages were reviewed. Conflicting or incomplete official information is left as a verification note instead of being filled with an assumption.</p><p>Data sources include university, scholarship-provider and government pages. Aggregator sites may help discovery, but do not serve as final evidence for a public record.</p></section><section><p className="kicker">How it is maintained</p><h2>AI-assisted, source-led, human accountable.</h2><p>AI helps discover, structure and recheck public information. Claims are linked to official sources, uncertain details remain marked as uncertain, and records distinguish verified facts from information that still needs confirmation.</p><p>This is a research aid, not an admissions service. Funding, deadlines and eligibility can change, so every applicant should verify the final details with the provider before applying.</p></section><section className="about-contact"><p className="kicker">Builder and corrections</p><h2>Hadi Budhy</h2><p>To suggest a correction or share an updated official source, contact Hadi through LinkedIn. Include the Scholarship Atlas page and the provider URL so the record can be rechecked.</p><div><a href="https://hadibudhy.github.io/" target="_blank" rel="noreferrer">View Hadi Budhy&apos;s portfolio</a><a href="https://www.linkedin.com/in/hadibudhy" target="_blank" rel="noreferrer">Contact Hadi Budhy on LinkedIn</a></div></section></article><SiteFooter /></main>;
}
