/* oxlint-disable next/no-html-link-for-pages -- GitHub Pages navigation must not depend on the client router. */
import { LandingRecords } from '@/components/landing-records';
import { SiteFooter, SiteHeader } from '@/components/site-header';
import { opportunities, researchDate, sortedOpportunities } from '@/lib/library';
import { JsonLd } from '@/lib/structured-data';

export default function Home() {
  const open = opportunities.filter((item) => ['OPEN', 'UPCOMING', 'OPEN_OR_UPCOMING', 'OPEN_OR_RECURRING', 'OPEN_OR_ROLLING'].includes(item.current_status ?? '')).length;
  const fullyFunded = opportunities.filter((item) => item.funding_classification === 'FULLY_FUNDED').length;
  const featured = sortedOpportunities(opportunities).slice(0, 8);
  return <main><JsonLd data={{ '@context': 'https://schema.org', '@type': 'Dataset', name: 'Scholarship Atlas graduate funding library', description: 'Official-source graduate funding records for Data, AI and related fields.', license: 'https://creativecommons.org/licenses/by/4.0/' }} /><SiteHeader /><section className="directory-intro site-shell home-intro"><div><p className="kicker">Master&apos;s and PhD funding</p><h1>Funding routes for Data and AI graduate study.</h1><p className="intro-copy">Scholarships, fellowships and graduate funding opportunities for Data, AI and related fields, researched from official sources.</p></div><dl className="research-stats"><div><dt>Opportunities</dt><dd>{opportunities.length}</dd></div><div><dt>Open or upcoming</dt><dd>{open}</dd></div><div><dt>Fully funded</dt><dd>{fullyFunded}</dd></div></dl></section><section className="directory-section site-shell" id="directory"><div className="section-top"><div><p className="kicker">Find funding</p><h2>Start with the database.</h2></div><p className="research-note">Updated {researchDate}</p></div><p className="research-note">Browse a few recently verified funding routes below, or use the full directory to filter all {opportunities.length} records.</p><LandingRecords items={featured} /><a className="directory-link" href="/directory/">Browse and filter every funding opportunity</a></section><section className="method-section" id="method"><div className="site-shell method-inner"><div><p className="kicker">How Scholarship Atlas works</p><h2>Evidence first. Assumptions never.</h2></div><div className="method-copy"><p>Each record links to the scholarship, programme and admissions sources used to verify it. Details that vary by university, year or applicant are marked instead of guessed.</p><p>Use the directory to compare funding, deadlines and requirements, then open the official source before you apply.</p></div></div></section><SiteFooter /></main>;
}
