import { LibraryDirectory } from '@/components/library-directory';
import Link from 'next/link';
import { countries, currentStatuses, excludedCount, fields, fundingClasses, opportunities, researchDate, sortedOpportunities, type Opportunity } from '@/lib/library';

export default function Home() {
  const featured = sortedOpportunities(opportunities).slice(0, 4);
  return <main><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">◎</span><span>Scholarship Atlas</span></Link><span className="topbar-note">Data &amp; AI Master&apos;s funding</span></header>
    <section className="hero shell"><div className="eyebrow">Official-source research library</div><h1>Find funding for the next chapter in data.</h1><p className="hero-copy">A carefully structured guide to Master&apos;s scholarships and funding routes in data science, artificial intelligence, machine learning and adjacent fields.</p><div className="stat-row"><div><strong>{opportunities.length}</strong><span>opportunities</span></div><div><strong>{countries.length}</strong><span>countries &amp; regions</span></div><div><strong>{opportunities.filter((item) => item.verification_status === 'VERIFIED').length}</strong><span>verified records</span></div></div></section>
    <section className="featured shell"><div className="section-heading"><div><div className="eyebrow">Start here</div><h2>Strongest records in the library</h2></div><span className="section-meta">Updated {researchDate}</span></div><div className="feature-grid">{featured.map((record) => <OpportunityCard key={record.opportunity_id} record={record} featured />)}</div></section>
    <section className="directory shell" id="directory"><div className="section-heading"><div><div className="eyebrow">Browse the library</div><h2>Structured discovery</h2></div><span className="section-meta">{excludedCount} records remain excluded from this public view</span></div><LibraryDirectory items={opportunities} countries={countries} fields={fields} fundingClasses={fundingClasses} currentStatuses={currentStatuses} /></section>
    <footer className="footer shell"><span>Scholarship Atlas</span><span>Facts can change. Always confirm details on the official source.</span></footer></main>;
}

function OpportunityCard({ record, featured = false }: { record: Opportunity; featured?: boolean }) { const program = record.programs?.[0]; return <Link className={`opportunity-card ${featured ? 'featured-card' : ''}`} href={`/opportunities/${record.opportunity_id}`}><div className="card-top"><span className={`badge ${record.verification_status === 'VERIFIED' ? 'badge-good' : 'badge-warm'}`}>{record.verification_status === 'VERIFIED' ? 'Verified' : 'Partially verified'}</span><span className="country">{record.provider_country ?? 'International'}</span></div><h3>{record.name}</h3><p className="provider">{record.provider_name}</p><p className="card-summary">{record.summary ?? 'Funding and admission information available in the record.'}</p><div className="card-bottom"><span>{program?.name ?? "Master's programme"}</span><span className="arrow">↗</span></div></Link>; }
