import { LibraryDirectory } from '@/components/library-directory';
import { SiteFooter, SiteHeader } from '@/components/site-header';
import { countries, currentStatuses, fields, fundingClasses, opportunities, researchDate } from '@/lib/library';

export default function Home() {
  const open = opportunities.filter((item) => ['OPEN', 'UPCOMING', 'OPEN_OR_UPCOMING', 'OPEN_OR_RECURRING', 'OPEN_OR_ROLLING'].includes(item.current_status ?? '')).length;
  const fullyFunded = opportunities.filter((item) => item.funding_classification === 'FULLY_FUNDED').length;
  return <main><SiteHeader /><section className="directory-intro site-shell home-intro"><div><p className="kicker">Master&apos;s and PhD funding</p><h1>Funding routes for Data and AI graduate study.</h1><p className="intro-copy">Scholarships, fellowships and graduate funding opportunities for Data, AI and related fields, researched from official sources.</p></div><dl className="research-stats"><div><dt>Opportunities</dt><dd>{opportunities.length}</dd></div><div><dt>Open or upcoming</dt><dd>{open}</dd></div><div><dt>Fully funded</dt><dd>{fullyFunded}</dd></div></dl></section><section className="directory-section site-shell" id="directory"><div className="section-top"><div><p className="kicker">Find funding</p><h2>Start with the database.</h2></div><p className="research-note">Updated {researchDate}</p></div><LibraryDirectory items={opportunities} countries={countries} fields={fields} fundingClasses={fundingClasses} currentStatuses={currentStatuses} mode="preview" /></section><section className="method-section" id="method"><div className="site-shell method-inner"><div><p className="kicker">How Scholarship Atlas works</p><h2>Evidence first. Assumptions never.</h2></div><div className="method-copy"><p>Each record links to the scholarship, programme and admissions sources used to verify it. Details that vary by university, year or applicant are marked instead of guessed.</p><p>Use the directory to compare funding, deadlines and requirements, then open the official source before you apply.</p></div></div></section><SiteFooter /></main>;
}
