'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import type { Opportunity } from '@/lib/library';
import { formatLabel, latestDeadline, sortedOpportunities } from '@/lib/library';

export function LibraryDirectory({ items, countries, fields, fundingClasses, currentStatuses }: { items: Opportunity[]; countries: string[]; fields: string[]; fundingClasses: string[]; currentStatuses: string[] }) {
  const [country, setCountry] = useState('All countries'); const [field, setField] = useState('All fields'); const [funding, setFunding] = useState('All funding levels'); const [status, setStatus] = useState('All application statuses'); const [sort, setSort] = useState('recommended');
  const filtered = useMemo(() => { const result = items.filter((item) => (country === 'All countries' || item.provider_country === country) && (field === 'All fields' || item.programs?.some((program) => program.field_tags?.includes(field))) && (funding === 'All funding levels' || item.funding_classification === funding) && (status === 'All application statuses' || item.current_status === status)); return sort === 'recommended' ? sortedOpportunities(result) : [...result].sort((a, b) => (latestDeadline(a) ?? '9999').localeCompare(latestDeadline(b) ?? '9999')); }, [country, field, funding, status, sort, items]);
  return <><div className="filters" aria-label="Filter opportunities"><Select label="Country" value={country} onChange={setCountry} options={['All countries', ...countries]} /><Select label="Field" value={field} onChange={setField} options={['All fields', ...fields]} /><Select label="Funding" value={funding} onChange={setFunding} options={['All funding levels', ...fundingClasses]} /><Select label="Status" value={status} onChange={setStatus} options={['All application statuses', ...currentStatuses]} /><Select label="Sort" value={sort} onChange={setSort} options={['recommended', 'deadline']} /></div><div className="directory-count">Showing <strong>{filtered.length}</strong> of {items.length} opportunities</div><div className="directory-grid">{filtered.map((record) => <DirectoryCard key={record.opportunity_id} record={record} />)}</div>{!filtered.length && <div className="empty-state">No opportunities match these filters. Try widening one of the selections.</div>}</>;
}
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="filter"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option} value={option}>{formatLabel(option)}</option>)}</select></label>; }
function DirectoryCard({ record }: { record: Opportunity }) { return <Link className="directory-card" href={`/opportunities/${record.opportunity_id}`}><div className="card-top"><span className="badge badge-neutral">{formatLabel(record.funding_classification)}</span><span className="country">{record.provider_country ?? 'International'}</span></div><h3>{record.name}</h3><p className="provider">{record.provider_name}</p><div className="mini-grid"><span><b>Programme</b>{record.programs?.[0]?.name ?? 'Unknown'}</span><span><b>Status</b>{formatLabel(record.current_status)}</span></div></Link>; }
