import { notFound } from 'next/navigation';
import Link from 'next/link';
import { formatLabel, opportunities, type Opportunity } from '@/lib/library';

export function generateStaticParams() { return opportunities.map((record) => ({ id: record.opportunity_id })); }
export function generateMetadata({ params }: { params: { id: string } }) { const record = opportunities.find((item) => item.opportunity_id === params.id); return record ? { title: `${record.name} | Scholarship Atlas`, description: record.summary } : {}; }

export default function OpportunityPage({ params }: { params: { id: string } }) { const record = opportunities.find((item) => item.opportunity_id === params.id); if (!record) notFound(); const item = record as Opportunity; const program = item.programs?.[0]; const funding = item.funding ?? {};
  return <main><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">◎</span><span>Scholarship Atlas</span></Link><Link className="topbar-note" href="/#directory">Back to library</Link></header><article className="detail shell"><Link className="back-link" href="/#directory">← All opportunities</Link><div className="detail-kicker"><span className={`badge ${item.verification_status === 'VERIFIED' ? 'badge-good' : 'badge-warm'}`}>{item.verification_status === 'VERIFIED' ? 'Verified' : 'Partially verified'}</span><span>{item.provider_country}</span><span>Last checked {item.last_verified ?? 'Unknown'}</span></div><h1>{item.name}</h1><p className="detail-provider">{item.provider_name} · {formatLabel(item.current_status)}</p><p className="detail-summary">{item.summary}</p><div className="detail-layout"><div><Section title="Funding"><InfoGrid values={[["Funding level",formatLabel(item.funding_classification)],["Tuition",funding.tuition_coverage],["Stipend",funding.stipend_amount],["Accommodation",funding.accommodation_type],["Health insurance",funding.health_insurance],["Travel / relocation",`${funding.travel ?? 'Unknown'} · ${funding.relocation ?? 'Unknown'}`]]} /></Section><Section title="Master’s programme">{program ? <><h2 className="program-name">{program.name}</h2><p className="body-copy">{program.admission_summary}</p><InfoGrid values={[["Duration",program.duration_text],["Language",program.language],["References",program.recommendation_count ?? program.recommendation_status],["Application fee",program.admission_fee]]} /></> : <p className="body-copy">Programme details are currently unknown.</p>}</Section><Section title="Eligibility, obligations and open questions"><p className="body-copy">International eligibility: <strong>{formatLabel(item.international_eligibility)}</strong></p>{item.obligations?.length ? <ul>{item.obligations.map((entry) => <li key={entry}>{entry}</li>)}</ul> : <p className="body-copy">No additional obligations stated.</p>}{item.unresolved_fields?.length ? <><h3 className="minor-heading">Still needs confirmation</h3><ul>{item.unresolved_fields.map((entry) => <li key={entry}>{entry}</li>)}</ul></> : null}</Section></div><aside className="source-panel"><h2>Official links</h2>{item.sources?.map((source) => <a className="source-link" href={source.url} target="_blank" rel="noreferrer" key={source.url}><span>{source.title ?? 'Official source'}</span><b>↗</b></a>)}<div className="source-note">Confirm current deadlines, eligibility and award terms directly with the provider before applying.</div></aside></div></article></main>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="detail-section"><div className="eyebrow">{title}</div>{children}</section>; }
function InfoGrid({ values }: { values: Array<[string, string | null | undefined]> }) { return <div className="info-grid">{values.map(([label,value]) => <div key={label}><b>{label}</b><span>{value || 'Unknown'}</span></div>)}</div>; }
