import Link from 'next/link';
import { notFound } from 'next/navigation';
import { SiteFooter, SiteHeader } from '@/components/site-header';
import { formatLabel, latestDeadline, opportunities, type Opportunity } from '@/lib/library';

export function generateStaticParams() { return opportunities.map((record) => ({ id: record.opportunity_id })); }
export function generateMetadata({ params }: { params: { id: string } }) { const record = opportunities.find((item) => item.opportunity_id === params.id); return record ? { title: `${record.name} | Scholarship Atlas`, description: record.summary } : {}; }

export default function OpportunityPage({ params }: { params: { id: string } }) { const record = opportunities.find((item) => item.opportunity_id === params.id); if (!record) notFound(); const item = record as Opportunity; const program = item.programs?.[0]; const funding = item.funding ?? {}; const deadline = latestDeadline(item);
  return <main><SiteHeader /><article className="record-page site-shell"><Link className="back-link" href="/#directory">Back to directory</Link><header className="record-header"><div className="record-status"><span className={`status ${item.verification_status === 'VERIFIED' ? 'verified' : 'partial'}`}>{item.verification_status === 'VERIFIED' ? 'Verified record' : 'Partially verified'}</span><span>{item.provider_country}</span><span>Checked {item.last_verified ?? 'Unknown'}</span></div><h1>{item.name}</h1><p className="record-provider">{item.provider_name}</p><p className="record-summary">{item.summary}</p></header><div className="record-layout"><div className="record-content"><section className="record-section"><p className="kicker">Funding at a glance</p><div className="fact-grid"><Fact label="Funding classification" value={formatLabel(item.funding_classification)} /><Fact label="Tuition coverage" value={funding.tuition_coverage} /><Fact label="Stipend" value={funding.stipend_amount} /><Fact label="Accommodation" value={funding.accommodation_type} /><Fact label="Health insurance" value={funding.health_insurance} /><Fact label="Next published date" value={deadline ?? 'Not published'} /></div></section><section className="record-section"><p className="kicker">Master&apos;s programme</p>{program ? <><h2>{program.name}</h2><p className="body-copy">{program.admission_summary}</p><div className="fact-grid compact"><Fact label="Duration" value={program.duration_text} /><Fact label="Language" value={program.language} /><Fact label="Recommendation letters" value={program.recommendation_count ?? program.recommendation_status} /><Fact label="Application fee" value={program.admission_fee} /></div></> : <p className="body-copy">Programme details are not published in this record.</p>}</section><section className="record-section"><p className="kicker">Eligibility and restrictions</p><p className="body-copy">International eligibility: <strong>{formatLabel(item.international_eligibility)}</strong></p>{item.obligations?.length ? <List entries={item.obligations} /> : <p className="body-copy">No additional obligations are stated.</p>}</section>{item.unresolved_fields?.length ? <section className="record-section unresolved"><p className="kicker">Still to confirm</p><h2>What this record does not claim yet.</h2><List entries={item.unresolved_fields} /></section> : null}</div><aside className="source-panel"><p className="kicker">Official sources</p><h2>Verify before you apply.</h2>{item.sources?.map((source) => <a className="source-link" href={source.url} target="_blank" rel="noreferrer" key={source.url}><span>{source.title ?? 'Official source'}</span><small>{formatLabel(source.source_role)}</small></a>)}<p className="source-note">External sources open in a new tab.</p></aside></div></article><SiteFooter /></main>; }
function Fact({ label, value }: { label: string; value: string | null | undefined }) { return <div className="fact"><dt>{label}</dt><dd>{value || 'Unknown'}</dd></div>; }
function List({ entries }: { entries: string[] }) { return <ul className="record-list">{entries.map((entry) => <li key={entry}>{entry}</li>)}</ul>; }
